version: "3"
services:
    db:
        container_name: mysql
        build:
            context: ../mysql-dev
            dockerfile: ../mysql-dev/Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: back-end
        links:
            - "db"
        build:
            context: ../../
            dockerfile: ./Containers/back-end-dev/Dockerfile
        ports:
            - "8000:8000"